//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleApp.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   値 : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Component_ValueLabel {
            get {
                return ResourceManager.GetString("Component_ValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダミーコンポーネントを作る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ComponentCreationButton_ContextMenu_CreateDummyComponents {
            get {
                return ResourceManager.GetString("ComponentCreationButton_ContextMenu_CreateDummyComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   説明 : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ComponentCreationDialog_DescriptionHeader {
            get {
                return ResourceManager.GetString("ComponentCreationDialog_DescriptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前 : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ComponentCreationDialog_NameHeader {
            get {
                return ResourceManager.GetString("ComponentCreationDialog_NameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイプ : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ComponentCreationDialog_TypeHeader {
            get {
                return ResourceManager.GetString("ComponentCreationDialog_TypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値 : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ComponentCreationDialog_ValueHeader {
            get {
                return ResourceManager.GetString("ComponentCreationDialog_ValueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイプに一致しない値が入力されています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ComponentCreationDialog_Warning_DifferentTypeValue {
            get {
                return ResourceManager.GetString("ComponentCreationDialog_Warning_DifferentTypeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前を入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ComponentCreationDialog_Warning_NoName {
            get {
                return ResourceManager.GetString("ComponentCreationDialog_Warning_NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   末尾の&quot;f&quot;は不要です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ComponentCreationDialog_Warning_NoNeedFloatSuffix {
            get {
                return ResourceManager.GetString("ComponentCreationDialog_Warning_NoNeedFloatSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値を入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ComponentCreationDialog_Warning_NoValue {
            get {
                return ResourceManager.GetString("ComponentCreationDialog_Warning_NoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既に同名のコンポーネントが存在します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ComponentCreationDialog_Warning_RegisteredName {
            get {
                return ResourceManager.GetString("ComponentCreationDialog_Warning_RegisteredName", resourceCulture);
            }
        }
    }
}
